# Generated by Django 4.2.14 on 2024-07-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_alter_todolist_created_alter_todolist_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='description',
            field=models.TextField(default='task', max_length=500),
            preserve_default=False,
        ),
    ]
